# Generated by Django 4.2.20 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('guests_qty', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
