# Generated by Django 4.2.20 on 2025-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.IntegerField(unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('guests_qty', models.IntegerField(default=1)),
            ],
        ),
    ]
