# Generated by Django 4.2.20 on 2025-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
