# Generated by Django 4.2.20 on 2025-05-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
    ]
