# Generated by Django 4.2.20 on 2025-05-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('want_newsletter', models.BooleanField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to='booking.booking')),
            ],
        ),
    ]
