# Generated by Django 4.2.20 on 2025-05-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0003_alter_booking_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('want_newsletter', models.BooleanField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to='booking.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
