# Generated by Django 4.2.20 on 2025-05-15 18:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('img', cloudinary.models.CloudinaryField(default='cld-sample-4', max_length=255, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('meal_category', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')])),
            ],
        ),
    ]
