# Generated by Django 4.2.20 on 2025-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_category',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
