# Generated by Django 4.2.20 on 2025-05-13 19:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_meal_category_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=cloudinary.models.CloudinaryField(default='cld-sample-4', max_length=255, verbose_name='image'),
        ),
    ]
